<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGr8AAVM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGr8AAVM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGr8AAVM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGr8AAVM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGr8AAVM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Gr8AAVM',
    'container.build_id' => '075cb0db',
    'container.build_time' => 1575991619,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGr8AAVM');
